version: '3.8'

services:
  # Nginx SSL Proxy
  nginx-ssl:
    image: nginx:alpine
    container_name: ems-ssl-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./ssl-certs:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ems-network

  # Backend Service
  backend:
    image: sanketsmane/ems-backend:v4.2
    container_name: ems-backend-ssl
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - FRONTEND_URL=https://ems.formonex.in
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - ems-network

  # Frontend Service
  frontend:
    image: sanketsmane/ems-frontend:v4.3
    container_name: ems-frontend-ssl
    ports:
      - "3000:80"
    depends_on:
      - nginx-ssl
    restart: unless-stopped
    networks:
      - ems-network

networks:
  ems-network:
    driver: bridge

volumes:
  ssl-certs: