version: '3.8'

services:
  backend:
    image: sanketsmane/ems-backend:latest
    container_name: ems-backend
    ports:
      - "8000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://hackable3030:f9pZaA7rmlUkQ97N@cluster0.o6vez6l.mongodb.net/employee-management-system?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your_super_secret_jwt_key_here_make_it_very_long_and_secure
      - JWT_EXPIRE=7d
      - EMAIL_ENABLED=true
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=formonexsolutions@gmail.com
      - EMAIL_PASS=hnkn kucq biqt fovt
      - EMAIL_FROM=formonexsolutions@gmail.com
      - FRONTEND_URL=http://localhost
      - CLOUDINARY_URL=cloudinary://564439426461569:yH7p_TOyWeEQjCfRaxwxxLc0FG0@dr7mlwdso
      - CLOUDINARY_CLOUD_NAME=dr7mlwdso
      - CLOUDINARY_API_KEY=564439426461569
      - CLOUDINARY_API_SECRET=yH7p_TOyWeEQjCfRaxwxxLc0FG0
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - ems-network
    restart: unless-stopped

  frontend:
    image: sanketsmane/ems-frontend:latest
    container_name: ems-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ems-network
    restart: unless-stopped

volumes:
  backend_uploads:

networks:
  ems-network:
    driver: bridge