#!/bin/bash

echo "🏗️  Docker Hub Repository Creation Guide"
echo "========================================"
echo ""
echo "1. Visit: https://hub.docker.com/repositories"
echo "2. Click 'Create Repository'"
echo "3. Create these repositories:"
echo ""
echo "   Repository: sanketsmane/ems-backend"
echo "   Description: Employee Management System - Backend API"
echo "   Visibility: Public (or Private)"
echo ""
echo "   Repository: sanketsmane/ems-frontend" 
echo "   Description: Employee Management System - Frontend React App"
echo "   Visibility: Public (or Private)"
echo ""
echo "4. Once created, return here and run the push script"
