name: Build and Push Docker Images v4.5

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'package.json'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for images'
        required: false
        default: 'v4.5'

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: sanketsmane/ems-backend
  FRONTEND_IMAGE: sanketsmane/ems-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for Backend
      id: meta-backend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.BACKEND_IMAGE }}
        tags: |
          type=raw,value=v4.5
          type=raw,value=latest
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - name: Extract metadata for Frontend
      id: meta-frontend
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.FRONTEND_IMAGE }}
        tags: |
          type=raw,value=v4.5
          type=raw,value=latest
          type=ref,event=branch
          type=sha,prefix={{branch}}-

    - name: Build and push Backend image
      id: docker_build_backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Frontend image
      id: docker_build_frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ steps.meta-frontend.outputs.tags }}
        labels: ${{ steps.meta-frontend.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Image digest
      run: |
        echo "Backend image pushed with digest: ${{ steps.docker_build_backend.outputs.digest }}"
        echo "Frontend image pushed with digest: ${{ steps.docker_build_frontend.outputs.digest }}"
        
    - name: Update deployment status
      run: |
        echo "🎉 Successfully built and pushed EMS v4.5 images!"
        echo "📦 Backend: ${{ env.BACKEND_IMAGE }}:v4.5"
        echo "📦 Frontend: ${{ env.FRONTEND_IMAGE }}:v4.5"
        echo "🌐 Docker Hub: https://hub.docker.com/u/sanketsmane"

    - name: Create deployment summary
      run: |
        cat << EOF > deployment-summary.md
        # EMS v4.5 Docker Images Deployed
        
        ## ✅ Successfully Pushed Images
        
        ### Backend
        - **Repository**: \`${{ env.BACKEND_IMAGE }}\`
        - **Tags**: \`v4.5\`, \`latest\`, \`main\`
        - **Platforms**: linux/amd64, linux/arm64
        - **Registry**: Docker Hub
        
        ### Frontend
        - **Repository**: \`${{ env.FRONTEND_IMAGE }}\`
        - **Tags**: \`v4.5\`, \`latest\`, \`main\`
        - **Platforms**: linux/amd64, linux/arm64
        - **Registry**: Docker Hub
        
        ## 🚀 Next Steps
        
        1. **Verify on Docker Hub**:
           - Backend: https://hub.docker.com/r/sanketsmane/ems-backend
           - Frontend: https://hub.docker.com/r/sanketsmane/ems-frontend
        
        2. **Deploy to Production**:
           \`\`\`bash
           ./deploy-v4.5.sh
           \`\`\`
        
        3. **Update Docker Compose**:
           \`\`\`yaml
           services:
             backend:
               image: sanketsmane/ems-backend:v4.5
             frontend:
               image: sanketsmane/ems-frontend:v4.5
           \`\`\`
        
        ## 📊 Build Information
        - **Triggered by**: ${{ github.event_name }}
        - **Branch**: ${{ github.ref_name }}
        - **Commit**: ${{ github.sha }}
        - **Build time**: $(date)
        - **Platforms**: Multi-architecture (amd64, arm64)
        
        ## 🔗 Useful Links
        - [GitHub Repository](https://github.com/${{ github.repository }})
        - [Docker Hub Profile](https://hub.docker.com/u/sanketsmane)
        - [Production Deployment Guide](./PRODUCTION_DEPLOYMENT_GUIDE.md)
        EOF

    - name: Upload deployment summary
      uses: actions/upload-artifact@v4
      with:
        name: deployment-summary
        path: deployment-summary.md